// <auto-generated />
namespace TokenAuth.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class adding_clientDeatils_Table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adding_clientDeatils_Table));
        
        string IMigrationMetadata.Id
        {
            get { return "202211141341213_adding_clientDeatils_Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
